spring:
  datasource:
#    url: ${DATABASE_URL}
#    username: ${SA_USER}
#    password: ${SA_PASSWORD}
    url: jdbc:postgresql://localhost:5432/cheap_lib
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
    show-sql: true