name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy_to_heroku:
    runs-on: ubuntu-latest
    name: Deploy application to heroku
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: "main"
      - name: Deploy app
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "cheap-lib"
          heroku_email: "hellojonas@gmail.com"
          buildpack: "https://github.com/heroku/heroku-buildpack-java.git"